fixtures:
  repositories:
    "stdlib": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    "vcsrepo": "git://github.com/puppetlabs/puppetlabs-vcsrepo.git"
    "apache": "git://github.com/puppetlabs/puppetlabs-apache.git"
    "mysql": "git://github.com/camptocamp/puppet-mysql.git"
  symlinks:
    "freepbx": "#{source_dir}"
