fixtures:
  forge_modules:
    apache: 'puppetlabs-apache'
    concat: 'puppetlabs-concat'
    mysql: 'puppetlabs-mysql'
    stdlib: 'puppetlabs-stdlib'
    vcsrepo: 'puppetlabs-vcsrepo'
  symlinks:
    freepbx: "#{source_dir}"
