fixtures:
  repositories:
    concat: https://github.com/puppetlabs/puppetlabs-concat
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib
    vcsrepo: https://github.com/puppetlabs/puppetlabs-vcsrepo
    apache: https://github.com/puppetlabs/puppetlabs-apache
    mysql: https://github.com/camptocamp/puppet-mysql
  symlinks:
    freepbx: "#{source_dir}"
